# Generated by Django 3.0.4 on 2020-09-28 21:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='categoria',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
