# Generated by Django 3.0.4 on 2020-09-28 21:13

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_auto_20200928_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.Categoria'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='contenido',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
