# Generated by Django 3.0.4 on 2020-10-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_auto_20200928_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
