# Generated by Django 3.0.4 on 2020-10-01 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0004_noticias_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Estatus Publicación'),
        ),
    ]
