# Generated by Django 3.0.4 on 2020-10-04 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0006_catalogogalerias_galerias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galerias',
            old_name='nombre_galeria',
            new_name='titulo',
        ),
    ]
