# Generated by Django 3.0.4 on 2020-10-04 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0007_auto_20201003_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True, verbose_name='Estatus')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'cursos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True, verbose_name='Estatus')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'estados',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NivelAcademico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_academico', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True, verbose_name='Estatus')),
            ],
            options={
                'verbose_name': 'Nivel Academicos',
                'verbose_name_plural': 'Nivel Academicos',
                'db_table': 'nivel_academicos',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelTable(
            name='noticias',
            table='noticias',
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=200)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.Estados')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'municipios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FormularioIncripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=8)),
                ('archivo_cedula', models.ImageField(upload_to='', verbose_name='Adjuntar Archivo Cedula')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('profesion', models.CharField(max_length=70)),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('telefono', models.IntegerField(max_length='12', verbose_name='Telefono')),
                ('telefono_local', models.IntegerField(max_length='12', verbose_name='Telefono Local')),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('curriculum', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Adjuntar Sintaxix Curricular')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.BooleanField(default=True, verbose_name='Estatus Registrado')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.Cursos')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.Estados')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.Municipios')),
                ('nivel_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.NivelAcademico')),
            ],
            options={
                'verbose_name': 'Formulario de Inscripción',
                'verbose_name_plural': 'Formulario de Inscripción',
                'db_table': 'formulario_inscripcion',
                'ordering': ['id'],
            },
        ),
    ]
