# Generated by Django 3.0.4 on 2020-10-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0008_auto_20201004_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioincripcion',
            name='curriculum',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Adjuntar Sintaxix Curricular'),
        ),
    ]
